name: Build App
description: Build app for Android
runs:
  using: composite
  steps:
    - uses: actions/checkout@v4

    - name: setup ruby env
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.1.2
        bundler-cache: true

#    print ruby version

    - name: print ruby version
      shell: bash
      run: ruby --version
    - name: Install bundler
      shell: bash
      run: |
        gem install bundler
        bundle config set --local path vendor/bundle
#        bundle install

    # Sets up a Java environment
    - name: Setup Java
      uses: actions/setup-java@v2 #v4
      with:
        distribution: "temurin" #"zulu"
        java-version: "17"

    # Sets up the Android SDK environment
    - name: Set up Android SDK
      uses: android-actions/setup-android@v2

    - name: Cache Gradle dependencies
      uses: actions/cache@v2
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle-

    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v4.3.3
      with:
       name: AndroidCICD.apk
       path: app/build/outputs/apk/debug/app-debug.apk

    #Fastlane execution
#    - name: Fastlane lane execution
#      shell: bash
#      run: bundle exec fastlane distribute