  name: :AndroidBuild

  on:
    pull_request:
      branches: [ master ]
    push:
     branches:
       - master

    #Allows you to run this action manually from the Action
    workflow_dispatch:

  jobs:
    build:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout
          uses: actions/checkout@v4.1.5

        - name: Build App
          uses: ./.github/actions

        - name: Setup Java JDK
          uses: actions/setup-java@v4.2.1
          with:
            java-version: '17'
            distribution: 'adopt'

        - name: Build with Gradle
          run: ./gradlew build


        - name: Upload a Build Artifact
          uses: actions/upload-artifact@v4.3.3
          with:
            name: AndroidCICD.apk
            path: app/build/outputs/apk/debug/app-debug.apk

        - name: Notify slack
          env:
              SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
          uses: abinoda/slack-action@master
          with:
            args: '{\"channel\":\"C07554HPTHT\",\"blocks\":[{\"type\":\"section\",\"text\":{\"type\":\"mrkdwn\",\"text\":\"*Pull Request:* ${{ github.event.pull_request.title }}\"}},{\"type\":\"section\",\"text\":{\"type\":\"mrkdwn\",\"text\":\"*Who?:* ${{ github.event.pull_request.user.login }}\n*Request State:* ${{ github.event.pull_request.state }}\"}},{\"type\":\"section\",\"text\":{\"type\":\"mrkdwn\",\"text\":\"<${{ github.event.pull_request.html_url }}|View Pull Request>\"}}]}'

