  name: slack
  on: [push]
  jobs:
   slack:
    runs-on: ubuntu-latest

    steps:
      - name: Notify slack
        env:
          LACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
        uses: pullreminders/slack-action@master
        with:
          args: '{\"channel\":\"C1234567890\",\"text\":\"Hello world\"}'
